### ISSUE TITLE
Use vendoring

### ISSUE THREAD

**Issue by nikhita** [go-openapi/validate#79]
I tried running a test but faced errors due to an old `go-openapi/loads` package. I believe vendoring would have solved such errors.

What do you think of introducing a vendor directory using any preferred dependency management system (maybe [dep](https://github.com/golang/dep))?

@sttts fyi

**Comment by fredbi** [comment]
Vendor and dep are configured in the "receptable" repository go-swagger/go-swagger, essentially because it is a full distribution, including some binary releases.

go-openapi packages have no such constraints. Basically, they are tested with all dependencies with most recent versions (e.g. go get ...), and we don't tag releases on these packages (at least for now).

If you are using this pkg independently (i.e; without go-swagger), you probably would have custom vendoring constraints that we may not know in advance.

**Comment by nikhita** [comment]
@fredbi :+1:
